[workspace]
members = ["lib/*", "crates/*"]
resolver = "2"

[workspace.package]
rust-version = "1.82"
edition = "2021"
license = "GPLv3+"
authors = ["Miquel Sabaté Solà"]

[workspace.dependencies]
xixanta = { path = "./lib/xixanta", version = "0.1.0" }
