[package]
name = "nasm"
version = "0.1.0"
edition = "2021"
authors = ["Miquel Sabaté Solà <mikisabate@gmail.com>"]

[dependencies]
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["derive"] }
xixanta.workspace = true
