name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: cargo test

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

      - name: Fuzzy testing
        run: |
          cd lib/xixanta
          cargo +nightly fuzz run fuzz_target_1 -- -max_total_time=180
